<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_54227be67e225',
	'title' => 'Portfolio Options',
	'fields' => array (
		array (
			'key' => 'field_54227be6907ec',
			'label' => 'Portfolio Layout',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_5437e5160b13d',
			'label' => 'Portfolio sidebar content',
			'name' => 'portfolio_sidebar_content',
			'prefix' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => array (
				'show' => 'True',
				'hided' => 'False',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5422892f9bc5f',
			'label' => 'Sticky sidebar using',
			'name' => 'display_sticky_sidebar',
			'prefix' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5437e5160b13d',
						'operator' => '==',
						'value'    => 'show',
					)
				)
			),
			'choices' => array (
				'show' => 'True',
				'hided' => 'False',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_54227be69087c',
			'label' => 'Show/Hide related portfolio',
			'name' => 'portfolio_display_related_post',
			'prefix' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => array (
				1 => 'Show',
				2 => 'Hide',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_54227be69088f',
			'label' => 'Portfolio information',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_54227ccb3b6d2',
			'label' => 'Portfolio size',
			'name' => 'portfolio_size',
			'prefix' => '',
			'type' => 'select',
			'instructions' => 'Only support Gallery Masonry Free Style',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => array (
				'small' => 'Small',
				'vertical' => 'Horizontal',
				'horizontal' => 'Vertical',
				'big' => 'Big',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_54227de93b6e1',
			'label' => 'Show/Hide meta',
			'name' => 'single_display_meta',
			'prefix' => '',
			'type' => 'select',
			'instructions' => 'Meta will be shown or not in single portfolio',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => array (
				'show' => 'Show',
				'hided' => 'Hide',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_54227ce43b6d3',
			'label' => 'Meta client',
			'name' => 'portfolio_client',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227cf23b6d4',
			'label' => 'Meta location',
			'name' => 'portfolio_location',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227d053b6d5',
			'label' => 'Meta period',
			'name' => 'portfolio_period',
			'prefix' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_54227d443b6d8',
			'label' => 'Meta custom label',
			'name' => 'portfolio_custom_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227d4f3b6d9',
			'label' => 'Meta custom value',
			'name' => 'portfolio_custom_value',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227d2b3b6d6',
			'label' => 'Meta text link button',
			'name' => 'portfolio_text_link',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227d373b6d7',
			'label' => 'Meta link button',
			'name' => 'portfolio_link',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5437e29d4a46e',
			'label' => 'Portfolio sidebar text',
			'name' => 'portfolio_sidebar_text',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					'rule_rule_rule_rule_0' => array(
						'field'    => 'field_54227de93b6e1',
						'operator' => '==',
						'value'    => 'show',
					),
				),
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227d7c3b6db',
			'label' => 'Hover link',
			'name' => 'hover_link',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227dcb3b6e0',
			'label' => 'Excerpt or Meta',
			'name' => 'portfolio_display_info',
			'prefix' => '',
			'type' => 'select',
			'instructions' => 'Only support template "Portfolio Text Masonry" and "Portfolio Text Gird"',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => array (
				'excerpt' => 'Excerpt',
				'meta' => 'Meta',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_54339f080e790',
			'label' => 'Portfolio format',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_54227d873b6dc',
			'label' => 'Portfolio Video format url',
			'name' => 'portfolio_video_format_url',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Option for format "video" only',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227d923b6dd',
			'label' => 'Portfolio video code',
			'name' => 'portfolio_video_code',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54339fe40e791',
			'label' => 'Portfolio Audio format url',
			'name' => 'portfolio_audio_format_url',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Option for format "audio" only',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54227da53b6de',
			'label' => 'Portfolio media',
			'name' => 'portfolio_media_file',
			'prefix' => '',
			'type' => 'file',
			'instructions' => 'Option for format "video" and "audio" only',
			'required' => 0,
			'conditional_logic' => 0,
			'return_format' => 'array',
			'library' => 'all',
		),
		array (
			'key' => 'field_54227db73b6df',
			'label' => 'Portfolio Gallery format',
			'name' => 'portfolio_gallery',
			'prefix' => '',
			'type' => 'gallery',
			'instructions' => 'Option for format "gallery" only',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post-portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
?>